# Gotta go fast
name: Smoke Test CI

on:
  workflow_call:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/install_zig.sh && ./zig/zig build install
